site_name: Zafira
pages:
    - Overview: index.md
    - Getting started: getting_started.md
    - Client setup: client_setup.md
    - Lifecycle: lifecycle.md
    - Integrations: integrations.md
    - Profile: profile.md
    - Dashboards: dashboards.md
    - Test runs: test_runs.md
    - User management: user_management.md
    - Release notes: releases.md

theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/zafira
repo_name: Github
